const actionTypes = {
    REGISTER_REQUEST: "REGISTER_REQUEST",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_ERROR: "REGISTER_ERROR",

    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_ERROR: "LOGIN_ERROR",

    GET_SETTINGS_REQUEST: "GET_SETTINGS_REQUEST",
    GET_SETTINGS_SUCCESS: "GET_SETTINGS_SUCCESS",
    GET_SETTINGS_ERROR: "GET_SETTINGS_ERROR",

    SAVE_TEST_RESULTS_POST_REQUEST: "SAVE_TEST_RESULTS_POST_REQUEST",
    SAVE_TEST_RESULTS_SUCCESS: "SAVE_TEST_RESULTS_SUCCESS",
    SAVE_TEST_RESULTS_POST_ERROR: "SAVE_TEST_RESULTS_POST_ERROR"
}

export default actionTypes;